image:https://travis-ci.org/esanchezros/quickfixj-spring-boot-starter.svg?branch=2.0.x["Build Status", link="https://travis-ci.org/esanchezros/quickfixj-spring-boot-starter"]
image:https://codecov.io/gh/esanchezros/quickfixj-spring-boot-starter/branch/2.0.x/graph/badge.svg["codecov",link="https://codecov.io/gh/esanchezros/quickfixj-spring-boot-starter"]
image:https://img.shields.io/badge/maven%20central-v2.6.0-blue.svg["Maven Central",link="https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22quickfixj-spring-boot-starter%22"]
image:https://img.shields.io/hexpm/l/plug.svg["Apache 2",link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/badge/quickfixj-2.2.0-blue.svg["QuickFIX/J 2.2.0", link="https://github.com/quickfix-j/quickfixj"]
image:https://api.codacy.com/project/badge/Grade/3fda9a73471c40e781617cfba9043950["Codacy code quality", link="https://www.codacy.com/app/esanchezros/quickfixj-spring-boot-starter?utm_source=github.com&utm_medium=referral&utm_content=esanchezros/quickfixj-spring-boot-starter&utm_campaign=Badge_Grade"]

= Spring Boot Starter for QuickFIX/J (Spring Boot 2)

This project is a https://spring.io/projects/spring-boot/[Spring Boot Starter] for https://github.com/quickfix-j/quickfixj[QuickFIX/J messaging engine for the FIX protocol].
It simplifies the configuration required to create and start an https://www.quickfixj.org/javadoc/2.1.0/quickfix/Initiator.html[Initiator] or https://www.quickfixj.org/javadoc/2.1.0/quickfix/Acceptor.html[Acceptor], and handles the lifecycle of the https://www.quickfixj.org/javadoc/2.1.0/quickfix/Connector.html[Connector].

*Examples:*
https://github.com/esanchezros/quickfixj-spring-boot-starter-examples[quickfixj-spring-boot-starter-examples]

* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/docker-server-client[QuickfixJ Server and Client applications as Docker containers]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/docker-server-client-with-failover[QuickfixJ Server and Client applications as Docker containers with server failover]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-and-server[QuickfixJ Server and Client application]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-listener[QuickfixJ Client application with Event Listeners]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client[QuickfixJ Client application]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-server-listener[QuickfixJ Server application with Event Listeners]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-server[QuickfixJ Server application]

== Getting started

To use the QuickFIX/J Server or QuickFIX/J Client you have to add the QuickFIX/J Spring Boot Starter dependency in your project.

[source,xml]
----
<dependency>
    <groupId>io.allune</groupId>
    <artifactId>quickfixj-spring-boot-starter</artifactId>
    <version>2.6.0</version>
</dependency>
----

To enable the actuator endpoints you will also have to add the QuickFIX/J Spring Boot Actuator dependency.

[source,xml]
----
<dependency>
    <groupId>io.allune</groupId>
    <artifactId>quickfixj-spring-boot-actuator</artifactId>
    <version>2.6.0</version>
</dependency>
----

=== QuickFIX/J Spring Boot Starter - Server

The `@EnableQuickFixJServer` will auto configure a QuickFIX/J Server:

[source,java]
----
@EnableQuickFixJServer
@SpringBootApplication
public class AppServer {

    public static void main(String[] args) {
        SpringApplication.run(AppServer.class, args);
    }
}
----

The configuration can be done in the application.properties / application.yml.

[source,yml]
----
quickfixj:
  server:
    config: classpath:quickfixj-server.cfg
----

Additionally you need to add a https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html[quickfixj-server.cfg]
file to configure the FIX sessions.
The configuration is resolved using the following approach:

* By the presence of a `quickfix.SessionSettings` bean named `serverSessionSettings`
* By a configuration file defined by the `quickfixj.server.config` property
* By the presence of the `quickfixj.server.config` system property
* By a `quickfixj-server.cfg` in the working directory or at the root of the classpath

==== QuickFIX/J Server properties

[source,properties]
----
quickfixj.server.config=classpath:quickfixj-server.cfg # location of the quickfixj acceptor
quickfixj.server.auto-startup=true # whether to auto-connect to the remote endpoint at start up
quickfixj.server.phase=0 # phase in which this connection manager should be started and stopped
quickfixj.server.jmx-enabled=true # whether to register the jmx mbeans for the acceptor
quickfixj.server.concurrent.enabled=true # whether to use a simple SocketAcceptor or a ThreadedSocketAcceptor
----

==== QuickFIX/J Server Actuator properties

[source,properties]
----
management.endpoint.quickfixjserver.enabled=true # whether the endpoint is enabled or not
management.endpoints.web.exposure.include=quickfixjserver # whether the endpoint will be exposed
----

Example usage:

    http://localhost:8081/actuator/quickfixjserver

[source,json]
----
{
  "FIX.4.2:EXEC->BANZAI": {
    "SenderCompID": "EXEC",
    "StartTime": "00:00:00",
    "DefaultMarketPrice": "12.30",
    "ValidOrderTypes": "1,2,F",
    "ConnectionType": "acceptor",
    "EndTime": "00:00:00",
    "BeginString": "FIX.4.2",
    "SocketAcceptPort": "9878",
    "TargetCompID": "BANZAI",
    "SenderCompID": "EXEC",
    "HeartBtInt": "30",
    "BeginString": "FIX.4.2",
    "TargetCompID": "BANZAI",
    "FileStorePath": "target/data/executor",
    "UseDataDictionary": "Y"
  },
  "FIX.4.1:EXEC->BANZAI": {
    "SenderCompID": "EXEC",
    "StartTime": "00:00:00",
    "DefaultMarketPrice": "12.30",
    "ValidOrderTypes": "1,2,F",
    "ConnectionType": "acceptor",
    "EndTime": "00:00:00",
    "BeginString": "FIX.4.1",
    "SocketAcceptPort": "9877",
    "TargetCompID": "BANZAI",
    "SenderCompID": "EXEC",
    "HeartBtInt": "30",
    "BeginString": "FIX.4.1",
    "TargetCompID": "BANZAI",
    "FileStorePath": "target/data/executor",
    "UseDataDictionary": "Y"
  }
}
----

=== QuickFIX/J Spring Boot Starter - Client

The `@EnableQuickFixJClient` will auto configure a QuickFIX/J Client:

[source,java]
----
@EnableQuickFixJClient
@SpringBootApplication
public class AppClient {

    public static void main(String[] args) {
        SpringApplication.run(AppClient.class, args);
    }
}
----

The configuration can be done in the application.properties / application.yml.

[source,yml]
----
quickfixj:
  client:
    config: classpath:quickfixj-client.cfg
----

Additionally you need to add a https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html[quickfixj-client.cfg]
file to configure the FIX sessions.
The configuration is resolved using the following approach:

* By the presence of a `quickfix.SessionSettings` bean named `clientSessionSettings`
* By a configuration file defined by the `quickfixj.client.config` property
* By the presence of the `quickfixj.client.config` system property
* By a `quickfixj-client.cfg` in the working directory or at the root of the classpath

==== QuickFIX/J Client properties

[source,properties]
----
quickfixj.client.config=classpath:quickfixj-client.cfg # location of the quickfixj initiator
quickfixj.client.auto-startup=true # whether to auto-connect to the remote endpoint at start up
quickfixj.client.phase=0 # phase in which this connection manager should be started and stopped
quickfixj.client.jmx-enabled=true # whether to register the jmx mbeans for the initiator
quickfixj.client.concurrent.enabled=true # whether to use a simple SocketInitiator or a ThreadedSocketInitiator
----

==== QuickFIX/J Client Actuator properties

[source,properties]
----
management.endpoint.quickfixjclient.enabled=true # whether the endpoint is enabled or not
management.endpoints.web.exposure.include=quickfixjclient # whether the endpoint will be exposed
----

Example usage:

    http://localhost:8080/actuator/quickfixjclient

[source,json]
----
{
  "FIXT.1.1:BANZAI->EXEC": {
    "SenderCompID": "BANZAI",
    "StartTime": "00:00:00",
    "ConnectionType": "initiator",
    "EndTime": "00:00:00",
    "BeginString": "FIXT.1.1",
    "ReconnectInterval": "5",
    "TargetCompID": "EXEC",
    "DefaultApplVerID": "FIX.5.0",
    "SocketConnectHost": "localhost",
    "SenderCompID": "BANZAI",
    "HeartBtInt": "30",
    "BeginString": "FIXT.1.1",
    "TargetCompID": "EXEC",
    "FileStorePath": "target/data/banzai",
    "SocketConnectPort": "9881"
  },
  "FIX.4.2:BANZAI->EXEC": {
    "SenderCompID": "BANZAI",
    "StartTime": "00:00:00",
    "ConnectionType": "initiator",
    "EndTime": "00:00:00",
    "BeginString": "FIX.4.2",
    "ReconnectInterval": "5",
    "TargetCompID": "EXEC",
    "SocketConnectHost": "localhost",
    "SenderCompID": "BANZAI",
    "HeartBtInt": "30",
    "BeginString": "FIX.4.2",
    "TargetCompID": "EXEC",
    "FileStorePath": "target/data/banzai",
    "SocketConnectPort": "9878"
  }
}
----

=== Listening on quickfixj.Application messages

The QuickFIX/J Spring Boot Starter provides a default implementation for the `quickfixj.Application` interface which publishes the messages received by the Server (Acceptor) and the Client (Initiator) as `ApplicationEvent`s.

If your application is only processing a subset of message types (i.e. `toAdmin`, `toApp`, `onCreate`, etc.) you will need to register an `EventListener` for these, with the appropriate message type as the only parameter for the listener method:

[source,java]
----
@EventListener
public void listenFromAdmin(FromAdmin fromAdmin) {
	...
}

@EventListener
public void listenFromApp(FromApp fromApp) {
	...
}

@EventListener
public void listenOnCreate(Create create) {
	...
}

@EventListener
public void listenOnLogon(Logon logon) {
	...
}

@EventListener
public void listenOnLogout(Logout logout) {
	...
}

@EventListener
public void listenToAdmin(ToAdmin toAdmin) {
	...
}

@EventListener
public void listenToApp(ToApp toApp) {
	...
}
----

In case the `EventListener` method throws an exception, this exception will be propagated up the `quickfix.Session#next()` method.
Depending on the value of `RejectMessageOnUnhandledException` in the quickfixj configuration file, the message will be redelivered or dismissed.

=== QuickFixJTemplate

The `QuickFixJTemplate` provides a synchronous client to perform requests, exposing a simple, template method API over the QuickFIX/J client.

`@EnableQuickFixJServer` provides a `serverQuickFixJTemplate` bean and `@EnableQuickFixJClient` provides a `clientQuickFixJTemplate` bean than can be `Autowired` in the application.

[source,java]
----
@Autowire
private QuickFixJTemplate serverQuickFixJTemplate;

...

SessionID sessionID = serverAcceptor.getSessions().stream()
        .filter(sessId ->
                sessId.getBeginString().equals(fixVersion) &&
                        sessId.getTargetCompID().equals(targetId))
        .findFirst()
        .orElseThrow(RuntimeException::new);

OrderCancelRequest message = new OrderCancelRequest(
        new OrigClOrdID("123"),
        new ClOrdID("321"),
        new Symbol("LNUX"),
        new Side(Side.BUY));

serverQuickFixJTemplate.send(message, sessionID);

----

=== License and Acknowledgement

The QuickFIX/J Spring Boot Starter is released under version 2.0 of the http://www.apache.org/licenses/LICENSE-2.0[Apache License].

This code includes software developed by http://www.quickfixengine.org/[quickfixengine.org].
