image:https://travis-ci.org/esanchezros/quickfixj-spring-boot-starter.svg?branch=2.0.x["Build Status", link="https://travis-ci.org/esanchezros/quickfixj-spring-boot-starter"]
image:https://codecov.io/gh/esanchezros/quickfixj-spring-boot-starter/branch/2.0.x/graph/badge.svg["codecov", link="https://codecov.io/gh/esanchezros/quickfixj-spring-boot-starter"]
image:https://img.shields.io/badge/maven%20central-v2.2.0-blue.svg["Maven Central", link="https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22quickfixj-spring-boot-starter%22"]
image:https://img.shields.io/hexpm/l/plug.svg["Apache 2", link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/badge/quickfixj-2.1.0-blue.svg["QuickFixJ 2.1.0", link="https://github.com/quickfix-j/quickfixj"]
image:https://api.codacy.com/project/badge/Grade/3fda9a73471c40e781617cfba9043950["Codacy code quality", link="https://www.codacy.com/app/esanchezros/quickfixj-spring-boot-starter?utm_source=github.com&utm_medium=referral&utm_content=esanchezros/quickfixj-spring-boot-starter&utm_campaign=Badge_Grade"]

= Spring Boot Starter for QuickFixJ (Spring Boot 2)

https://github.com/quickfix-j/quickfixj

*Examples:*
https://github.com/esanchezros/quickfixj-spring-boot-starter-examples[quickfixj-spring-boot-starter-examples]

* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/quickfixj-spring-boot-starter-example-client[Client]
* https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/quickfixj-spring-boot-starter-example-server[Server]

This project is a https://spring.io/projects/spring-boot/[Spring Boot Starter] for QuickFixJ.
It simplifies the configuration required to create and start an Initiator or Acceptor, and handles the lifecycle of the Connector.

== Getting started

To use the QuickFixJ Server or QuickFixJ Client you have to add the QuickFixJ Spring Boot Starter dependency in
your project.

[source, xml]
----
<dependency>
	<groupId>io.allune</groupId>
	<artifactId>quickfixj-spring-boot-starter</artifactId>
	<version>2.2.0</version>
</dependency>
----

To enable the actuator endpoints you will also have to add the QuickFixJ Spring Boot Actuator dependency.

[source, xml]
----
<dependency>
    <groupId>io.allune</groupId>
    <artifactId>quickfixj-spring-boot-actuator</artifactId>
	<version>2.2.0</version>
</dependency>
----

=== QuickFixJ Spring Boot Starter - Server

The `@EnableQuickFixJServer` will auto configure a QuickFixJ Server:

[source, java]
----
@EnableQuickFixJServer
@SpringBootApplication
public class AppServer {

    public static void main(String[] args) {
        SpringApplication.run(AppServer.class, args);
    }
}
----

The configuration can be done in the application.properties / application.yml.

[source, yml]
----
quickfixj:
  server:
    config: classpath:quickfixj-server.cfg
----

Additionally you need to add a https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html[quickfix-server.cfg]
file to configure the FIX sessions. The configuration is resolved using the following approach:

* By the presence of a `quickfix.SessionSettings` bean named `serverSessionSettings`
* By a configuration file defined by the `quickfixj.server.config` property
* By the presence of the `quickfixj.server.config` system property
* By a `quickfixj-server.cfg` in the working directory or at the root of the classpath


==== QuickFixJ Server properties

[source, properties]
----
quickfixj.server.config=classpath:quickfixj-server.cfg # location of the quickfixj acceptor
quickfixj.server.auto-startup=true # whether to auto-connect to the remote endpoint at start up
quickfixj.server.phase=0 # phase in which this connection manager should be started and stopped
quickfixj.server.jmx-enabled=true # whether to register the jmx mbeans for the acceptor
quickfixj.server.concurrent.enabled=true # whether to use a simple SocketAcceptor or a ThreadedSocketAcceptor
----

==== QuickFixJ Server Actuator properties

[source, properties]
----
management.endpoint.quickfixjserver.enabled=true # whether the endpoint is enabled or not
management.endpoints.web.exposure.include=quickfixjserver # whether the endpoint will be exposed
----

Example usage:

    http://localhost:8081/actuator/quickfixjserver

[source, json]
----
{
  "FIX.4.2:EXEC->BANZAI": {
    "SenderCompID": "EXEC",
    "StartTime": "00:00:00",
    "DefaultMarketPrice": "12.30",
    "ValidOrderTypes": "1,2,F",
    "ConnectionType": "acceptor",
    "EndTime": "00:00:00",
    "BeginString": "FIX.4.2",
    "SocketAcceptPort": "9878",
    "TargetCompID": "BANZAI",
    "SenderCompID": "EXEC",
    "HeartBtInt": "30",
    "BeginString": "FIX.4.2",
    "TargetCompID": "BANZAI",
    "FileStorePath": "target/data/executor",
    "UseDataDictionary": "Y"
  },
  "FIX.4.1:EXEC->BANZAI": {
    "SenderCompID": "EXEC",
    "StartTime": "00:00:00",
    "DefaultMarketPrice": "12.30",
    "ValidOrderTypes": "1,2,F",
    "ConnectionType": "acceptor",
    "EndTime": "00:00:00",
    "BeginString": "FIX.4.1",
    "SocketAcceptPort": "9877",
    "TargetCompID": "BANZAI",
    "SenderCompID": "EXEC",
    "HeartBtInt": "30",
    "BeginString": "FIX.4.1",
    "TargetCompID": "BANZAI",
    "FileStorePath": "target/data/executor",
    "UseDataDictionary": "Y"
  }
}
----

=== QuickFixJ Spring Boot Starter - Client

The `@EnableQuickFixJClient` will auto configure a QuickFixJ Client:

[source, java]
----
@EnableQuickFixJClient
@SpringBootApplication
public class AppClient {

    public static void main(String[] args) {
        SpringApplication.run(AppClient.class, args);
    }
}
----

The configuration can be done in the application.properties / application.yml.

[source,yml]
----
quickfixj:
  client:
    config: classpath:quickfixj-client.cfg
----

Additionally you need to add a https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html[quickfix-client.cfg]
file to configure the FIX sessions. The configuration is resolved using the following approach:

* By the presence of a `quickfix.SessionSettings` bean named `clientSessionSettings`
* By a configuration file defined by the `quickfixj.client.config` property
* By the presence of the `quickfixj.client.config` system property
* By a `quickfixj-client.cfg` in the working directory or at the root of the classpath

==== QuickFixJ Client properties

[source, properties]
----
quickfixj.client.config=classpath:quickfixj-client.cfg # location of the quickfixj initiator
quickfixj.client.auto-startup=true # whether to auto-connect to the remote endpoint at start up
quickfixj.client.phase=0 # phase in which this connection manager should be started and stopped
quickfixj.client.jmx-enabled=true # whether to register the jmx mbeans for the initiator
quickfixj.client.concurrent.enabled=true # whether to use a simple SocketInitiator or a ThreadedSocketInitiator
----

==== QuickFixJ Client Actuator properties

[source, properties]
----
management.endpoint.quickfixjclient.enabled=true # whether the endpoint is enabled or not
management.endpoints.web.exposure.include=quickfixjclient # whether the endpoint will be exposed
----

Example usage:

    http://localhost:8080/actuator/quickfixjclient

[source, json]
----
{
  "FIXT.1.1:BANZAI->EXEC": {
    "SenderCompID": "BANZAI",
    "StartTime": "00:00:00",
    "ConnectionType": "initiator",
    "EndTime": "00:00:00",
    "BeginString": "FIXT.1.1",
    "ReconnectInterval": "5",
    "TargetCompID": "EXEC",
    "DefaultApplVerID": "FIX.5.0",
    "SocketConnectHost": "localhost",
    "SenderCompID": "BANZAI",
    "HeartBtInt": "30",
    "BeginString": "FIXT.1.1",
    "TargetCompID": "EXEC",
    "FileStorePath": "target/data/banzai",
    "SocketConnectPort": "9881"
  },
  "FIX.4.2:BANZAI->EXEC": {
    "SenderCompID": "BANZAI",
    "StartTime": "00:00:00",
    "ConnectionType": "initiator",
    "EndTime": "00:00:00",
    "BeginString": "FIX.4.2",
    "ReconnectInterval": "5",
    "TargetCompID": "EXEC",
    "SocketConnectHost": "localhost",
    "SenderCompID": "BANZAI",
    "HeartBtInt": "30",
    "BeginString": "FIX.4.2",
    "TargetCompID": "EXEC",
    "FileStorePath": "target/data/banzai",
    "SocketConnectPort": "9878"
  }
}
----

=== License and Acknowledgement

The QuickFixJ Spring Boot Starter is released under version 2.0 of the http://www.apache.org/licenses/LICENSE-2.0[Apache License].

This code includes software developed by http://www.quickfixengine.org/[quickfixengine.org].
